# Generated by Django 3.1.2 on 2020-10-13 13:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='book_inf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(max_length=150, null=True, verbose_name='назвние книги')),
                ('author', models.CharField(max_length=100, null=True, verbose_name='автор')),
                ('rate', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг книги')),
                ('discriptions', models.TextField(verbose_name='описание книги')),
            ],
        ),
        migrations.CreateModel(
            name='users_inf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='Имя')),
                ('surname', models.CharField(max_length=100, null=True, verbose_name='Фамилия')),
                ('image', models.ImageField(blank=True, default='puples_photo/default.png', upload_to='puples_photo', verbose_name='Фотография профиля')),
                ('cal', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Связь с таблицей пользователей')),
            ],
        ),
    ]
