# Generated by Django 3.1.2 on 2020-10-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_inf',
            name='bookimage',
            field=models.ImageField(blank=True, default='puples_photo/default.png', upload_to='puples_photo', verbose_name='Фотография книги'),
        ),
    ]
