# Generated by Django 3.1.2 on 2020-10-13 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0003_auto_20201013_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users_inf',
            name='cal',
        ),
        migrations.RemoveField(
            model_name='users_inf',
            name='name',
        ),
        migrations.RemoveField(
            model_name='users_inf',
            name='surname',
        ),
        migrations.AddField(
            model_name='users_inf',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
