# Generated by Django 2.2.16 on 2020-10-14 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ebook', '0004_auto_20201013_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='users_inf',
            name='status',
            field=models.CharField(choices=[('ST', 'Ученик'), ('SADM', 'Администратор'), ('LIBR', 'Библиотекарь')], default='ST', max_length=30, verbose_name='Статуc'),
        ),
        migrations.CreateModel(
            name='userbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booksid', models.CharField(default='', max_length=30, verbose_name='id книги')),
                ('user', models.OneToOneField(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Связь с таблицей пользователей')),
            ],
        ),
    ]
