# Generated by Django 3.1.2 on 2020-10-16 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0005_auto_20201014_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='users_inf',
            name='gardesymbol',
            field=models.CharField(default='', max_length=1, verbose_name='Символ класса'),
        ),
        migrations.AddField(
            model_name='users_inf',
            name='grade',
            field=models.IntegerField(default='-1', max_length=1, verbose_name='Класс'),
        ),
    ]
