# Generated by Django 3.1.2 on 2020-10-16 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0006_auto_20201016_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_inf',
            name='grade',
            field=models.IntegerField(default='-1', verbose_name='Класс'),
        ),
    ]
