# Generated by Django 3.1.2 on 2020-10-16 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0007_auto_20201016_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_inf',
            name='gardesymbol',
            field=models.CharField(default='-', max_length=1, verbose_name='Символ класса'),
        ),
    ]
