# Generated by Django 3.0.7 on 2020-11-17 18:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0008_auto_20201016_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbook',
            name='booksid',
        ),
        migrations.AddField(
            model_name='book_inf',
            name='addingDate',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата добавления'),
        ),
        migrations.AddField(
            model_name='book_inf',
            name='bookfile',
            field=models.FileField(default='puples_photo/default.png', upload_to='books'),
        ),
        migrations.AddField(
            model_name='userbook',
            name='book',
            field=models.OneToOneField(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='ebook.book_inf', verbose_name='Связь с таблицей книг'),
        ),
        migrations.AddField(
            model_name='userbook',
            name='enddate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='userbook',
            name='getdate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='userbook',
            name='reqestdate',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата добавления'),
        ),
        migrations.AddField(
            model_name='userbook',
            name='status',
            field=models.CharField(choices=[('True', 'Подтверждено библиотекарем'), ('False', 'В обработке'), ('Refused', 'Отказано')], default='False', max_length=30, verbose_name='Статуc'),
        ),
    ]
